/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cse5233.hw1;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.setSize(800, 400);
        f.setLayout(null);
        f.setVisible(true);
    }
}
