/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cse5233.hw1;

import cse5233.hw1.view.EditDiagramJFrame;
import cse5233.hw1.view.EditDiagramJFrameFactory;

public class App {
    public static void main(String[] args) {
        EditDiagramJFrame frame = new EditDiagramJFrameFactory().create();
        frame.setVisible(true);
    }
}
