/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cse5233.hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assert true;
    }
}
